### ISSUE TITLE
SB3 Project Page

### ISSUE THREAD

**Issue by araffin** [Rhoban/frasa#1]
Hello @MarcDcls ,

as I told @cgaspard3333 for https://github.com/Rhoban/footstepnet_envs, it would be nice if you could do a PR to add this repo to the SB3 project page.

Thanks =)

**Comment by araffin** [comment]
PS: fyi, I created a fork, reformated files, added python 3.9 compat, gymnasium 1.0 compat and fix some linter warnings in https://github.com/Rhoban/frasa/compare/main...araffin:frasa:fix/py39?expand=1

**Comment by araffin** [comment]
small ping ;)

**Comment by MarcDcls** [comment]
Done !
